# Generated by Django 4.2.2 on 2023-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_employee_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
