# Generated by Django 4.2.2 on 2023-06-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_employee_is_full_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('jr', 'Junior'), ('reg', 'Regular'), ('sr', 'Senior')], max_length=3),
        ),
    ]
