# Generated by Django 4.1.3 on 2023-06-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_fill_slug_for_existing_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(default='none', unique=True),
            preserve_default=False,
        ),
    ]
